# 公共配置yml文件
spring:
  profiles:
#启动执行哪个配置文件 不填 默认是default文件
    active: prod
  application:
    name: user_center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hjy
    url: jdbc:mysql://localhost:3306/louis
  #超时  session 失效时间一天
  session:
    timeout: 86400
    store-type: redis # none表示默认存储在内容中 存在redis
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # redis配置
  redis:
    port: 6379
    host: localhost
    database: 3
#  redis:
#    open: false  # 是否开启redis缓存  true开启   false关闭
#    database: 0
#    host: 119.29.252.106
#    port: 6379
#    password: 947410   # 密码（默认为空）
#    timeout: 6000ms  # 连接超时时长（毫秒）
server:
  port: 8081
  servlet:
    context-path: /api # 访问后端资源前缀
    session:
      cookie:
        domain: localhost
        same-site: none
        secure: true
# ??mybatisplus????????????
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    db-config:
      logic-delete-field: idDelete # ????????????(since 3.3.0,????????????2)
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)

